---
- hosts: vagranthosts
  sudo: yes
  tasks:
    - name: Install epel-releases
      yum: pkg=epel-release state=installed

    - name: Installs nginx web Server
      yum: pkg=nginx state=installed
      notify:
        - start nginx

  handlers:
    - name: start nginx
      service: name=nginx state=started
