---
- hosts: vagrant
  sudo: yes
  tasks:
    - name: Install epel-releases
      yum: pkg:epel-release state=installed

    - name: Installs ngnix web Server
      yum: pkg=ngnix state=installed
      notify:
        - start ngnix

  handlers:
    - name: start ngnix
      service: name=ngnix state=started
